const articles = [
  {
    id: 0,
    title: "Unique Night Events",
    type: "Party Ideas",
    createdAt: "2021-02-01",
    updatedAt: "",
    authorId: 0,
    authorName: "Paul Caughell",
    img: "https://archzine.com/wp-content/uploads/2019/06/outdoor-movie-night-teen-birthday-party-ideas-throw-pillows-fairy-lights.jpg",
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non ex sagittis, dignissim tellus ut, laoreet massa. Nulla libero arcu, imperdiet ut neque ac, fringilla tempor justo. Fusce maximus blandit sapien, id maximus odio malesuada nec. In hac habitasse platea dictumst. Nam eu cursus ex, vel rhoncus felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec efficitur dapibus tellus, ac tincidunt est rhoncus nec. Proin vitae purus eu arcu pellentesque dignissim sodales quis mi. Donec mauris augue, dignissim eget nunc sit amet, molestie euismod lorem. Curabitur ac egestas eros. Proin sed tellus tempor, congue elit vel, convallis nisl. Suspendisse porttitor mauris risus, vel tristique nulla dapibus eget. Nullam imperdiet magna eu sapien consequat scelerisque. Sed vel augue nisl. Nullam fermentum ac nunc eu vestibulum. Nam auctor massa laoreet sem hendrerit, vitae scelerisque elit venenatis.",
      "Maecenas iaculis nisi nec erat sollicitudin, ac pulvinar nisl tempus. Nunc rutrum consectetur erat, eget interdum dolor dignissim quis. Sed quis rutrum mauris. Ut tristique at mi eu consectetur. Proin et euismod mi, id scelerisque tortor. Suspendisse consectetur, tortor sit amet facilisis porta, ligula leo convallis arcu, sit amet dictum urna metus nec metus. Quisque dictum eget massa id aliquam. Curabitur gravida nunc eu massa lobortis iaculis. Morbi orci orci, tempor quis quam at, dictum sollicitudin enim. Duis quis vulputate libero. Phasellus venenatis ultrices venenatis. Suspendisse id sapien sed lacus pulvinar egestas nec ac ante.",
      "Maecenas libero elit, ullamcorper vel leo at, dignissim tempus risus. Aenean efficitur ipsum quis augue pellentesque consequat. Donec pharetra porttitor volutpat. Mauris eu neque ac libero congue posuere cursus at ligula. Aliquam erat volutpat. Nunc felis leo, varius ut laoreet in, iaculis id quam. Integer convallis mi eu sapien placerat hendrerit. Morbi odio leo, vehicula lacinia imperdiet vitae, tincidunt et libero. Suspendisse posuere consequat tortor at pretium. Nulla enim mauris, viverra commodo aliquam ac, pulvinar volutpat quam.",
    ],
  },
  {
    id: 2,
    title: "Simple Touches",
    type: "Party Ideas",
    createdAt: "2021-02-08",
    updatedAt: "",
    authorId: 0,
    authorName: "Paul Caughell",
    img: "http://www.weddingtentsale.com/wp-content/uploads/2017/02/shelter-party-tent-luxury-wedding-tent-social-event-tent-sports-cover-dome-geodisic-22.jpg",
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non ex sagittis, dignissim tellus ut, laoreet massa. Nulla libero arcu, imperdiet ut neque ac, fringilla tempor justo. Fusce maximus blandit sapien, id maximus odio malesuada nec. In hac habitasse platea dictumst. Nam eu cursus ex, vel rhoncus felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec efficitur dapibus tellus, ac tincidunt est rhoncus nec. Proin vitae purus eu arcu pellentesque dignissim sodales quis mi. Donec mauris augue, dignissim eget nunc sit amet, molestie euismod lorem. Curabitur ac egestas eros. Proin sed tellus tempor, congue elit vel, convallis nisl. Suspendisse porttitor mauris risus, vel tristique nulla dapibus eget. Nullam imperdiet magna eu sapien consequat scelerisque. Sed vel augue nisl. Nullam fermentum ac nunc eu vestibulum. Nam auctor massa laoreet sem hendrerit, vitae scelerisque elit venenatis.",
      "Maecenas iaculis nisi nec erat sollicitudin, ac pulvinar nisl tempus. Nunc rutrum consectetur erat, eget interdum dolor dignissim quis. Sed quis rutrum mauris. Ut tristique at mi eu consectetur. Proin et euismod mi, id scelerisque tortor. Suspendisse consectetur, tortor sit amet facilisis porta, ligula leo convallis arcu, sit amet dictum urna metus nec metus. Quisque dictum eget massa id aliquam. Curabitur gravida nunc eu massa lobortis iaculis. Morbi orci orci, tempor quis quam at, dictum sollicitudin enim. Duis quis vulputate libero. Phasellus venenatis ultrices venenatis. Suspendisse id sapien sed lacus pulvinar egestas nec ac ante.",
      "Maecenas libero elit, ullamcorper vel leo at, dignissim tempus risus. Aenean efficitur ipsum quis augue pellentesque consequat. Donec pharetra porttitor volutpat. Mauris eu neque ac libero congue posuere cursus at ligula. Aliquam erat volutpat. Nunc felis leo, varius ut laoreet in, iaculis id quam. Integer convallis mi eu sapien placerat hendrerit. Morbi odio leo, vehicula lacinia imperdiet vitae, tincidunt et libero. Suspendisse posuere consequat tortor at pretium. Nulla enim mauris, viverra commodo aliquam ac, pulvinar volutpat quam.",
    ],
  },
  {
    id: 3,
    title: "Lighting Ideas",
    type: "Party Ideas",
    createdAt: "2020-01-15",
    updatedAt: "",
    authorId: 0,
    authorName: "Paul Caughell",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXm0ZrSYCZq4kLQDttaDZhf-J6w0EhLkd15U580prIauPa2XBDmA&s",
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non ex sagittis, dignissim tellus ut, laoreet massa. Nulla libero arcu, imperdiet ut neque ac, fringilla tempor justo. Fusce maximus blandit sapien, id maximus odio malesuada nec. In hac habitasse platea dictumst. Nam eu cursus ex, vel rhoncus felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec efficitur dapibus tellus, ac tincidunt est rhoncus nec. Proin vitae purus eu arcu pellentesque dignissim sodales quis mi. Donec mauris augue, dignissim eget nunc sit amet, molestie euismod lorem. Curabitur ac egestas eros. Proin sed tellus tempor, congue elit vel, convallis nisl. Suspendisse porttitor mauris risus, vel tristique nulla dapibus eget. Nullam imperdiet magna eu sapien consequat scelerisque. Sed vel augue nisl. Nullam fermentum ac nunc eu vestibulum. Nam auctor massa laoreet sem hendrerit, vitae scelerisque elit venenatis.",
      "Maecenas iaculis nisi nec erat sollicitudin, ac pulvinar nisl tempus. Nunc rutrum consectetur erat, eget interdum dolor dignissim quis. Sed quis rutrum mauris. Ut tristique at mi eu consectetur. Proin et euismod mi, id scelerisque tortor. Suspendisse consectetur, tortor sit amet facilisis porta, ligula leo convallis arcu, sit amet dictum urna metus nec metus. Quisque dictum eget massa id aliquam. Curabitur gravida nunc eu massa lobortis iaculis. Morbi orci orci, tempor quis quam at, dictum sollicitudin enim. Duis quis vulputate libero. Phasellus venenatis ultrices venenatis. Suspendisse id sapien sed lacus pulvinar egestas nec ac ante.",
      "Maecenas libero elit, ullamcorper vel leo at, dignissim tempus risus. Aenean efficitur ipsum quis augue pellentesque consequat. Donec pharetra porttitor volutpat. Mauris eu neque ac libero congue posuere cursus at ligula. Aliquam erat volutpat. Nunc felis leo, varius ut laoreet in, iaculis id quam. Integer convallis mi eu sapien placerat hendrerit. Morbi odio leo, vehicula lacinia imperdiet vitae, tincidunt et libero. Suspendisse posuere consequat tortor at pretium. Nulla enim mauris, viverra commodo aliquam ac, pulvinar volutpat quam.",
      "Solo en T-mobile",
    ],
  },
  {
    id: 4,
    title: "Safety & Monitoring",
    type: "Party Ideas",
    createdAt: "2009-12-31",
    updatedAt: "2020-03-12",
    authorId: 0,
    authorName: "Paul Caughell",
    img: "https://tooelecity.org/wp-content/uploads/2015/03/Bounce-House-2.jpg",
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non ex sagittis, dignissim tellus ut, laoreet massa. Nulla libero arcu, imperdiet ut neque ac, fringilla tempor justo. Fusce maximus blandit sapien, id maximus odio malesuada nec. In hac habitasse platea dictumst. Nam eu cursus ex, vel rhoncus felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec efficitur dapibus tellus, ac tincidunt est rhoncus nec. Proin vitae purus eu arcu pellentesque dignissim sodales quis mi. Donec mauris augue, dignissim eget nunc sit amet, molestie euismod lorem. Curabitur ac egestas eros. Proin sed tellus tempor, congue elit vel, convallis nisl. Suspendisse porttitor mauris risus, vel tristique nulla dapibus eget. Nullam imperdiet magna eu sapien consequat scelerisque. Sed vel augue nisl. Nullam fermentum ac nunc eu vestibulum. Nam auctor massa laoreet sem hendrerit, vitae scelerisque elit venenatis.",
      "Maecenas iaculis nisi nec erat sollicitudin, ac pulvinar nisl tempus. Nunc rutrum consectetur erat, eget interdum dolor dignissim quis. Sed quis rutrum mauris. Ut tristique at mi eu consectetur. Proin et euismod mi, id scelerisque tortor. Suspendisse consectetur, tortor sit amet facilisis porta, ligula leo convallis arcu, sit amet dictum urna metus nec metus. Quisque dictum eget massa id aliquam. Curabitur gravida nunc eu massa lobortis iaculis. Morbi orci orci, tempor quis quam at, dictum sollicitudin enim. Duis quis vulputate libero. Phasellus venenatis ultrices venenatis. Suspendisse id sapien sed lacus pulvinar egestas nec ac ante.",
      "Maecenas libero elit, ullamcorper vel leo at, dignissim tempus risus. Aenean efficitur ipsum quis augue pellentesque consequat. Donec pharetra porttitor volutpat. Mauris eu neque ac libero congue posuere cursus at ligula. Aliquam erat volutpat. Nunc felis leo, varius ut laoreet in, iaculis id quam. Integer convallis mi eu sapien placerat hendrerit. Morbi odio leo, vehicula lacinia imperdiet vitae, tincidunt et libero. Suspendisse posuere consequat tortor at pretium. Nulla enim mauris, viverra commodo aliquam ac, pulvinar volutpat quam.",
      "Pellentesque non nulla quam. Etiam vitae sapien ullamcorper, convallis odio efficitur, tristique augue. Sed luctus nibh sapien, id volutpat neque sollicitudin eu. Fusce interdum volutpat sapien, non malesuada massa. Suspendisse potenti. Vivamus facilisis, quam nec pellentesque dignissim, ante dui vehicula arcu, in porta diam leo at augue. Praesent quis finibus lacus. Etiam dapibus ultricies dictum. Phasellus sodales mauris quam, quis pretium justo pharetra nec. Aenean ornare leo vitae massa faucibus interdum. Aliquam orci metus, tincidunt id posuere eu, pharetra in ligula.",
    ],
  },
];

export default articles;
