import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Article from "../../components/Article";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { productSearch, productSearchFiltered } from "../../utils/API";
import { Menu, Dropdown, Slider, InputNumber, Checkbox } from "antd";
import moment from "moment";

export default function article() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  console.log(router.route);
  return (
    <div>
      <Head>
        <title>Search Rentals - City of Bounce</title>
        <meta
          property="og:title"
          content={"Party Rentals | Bounce Houses | Tents - City of Bounce"}
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="content">
        <h3 className="bold">What?</h3>
        <Article />
      </div>
    </div>
  );
}
