import Head from 'next/head'
import { useRef, useState } from 'react'
import { Button, DatePicker } from 'antd';
import Image from 'next/image'
import Link from 'next/link'
import  globals from "../styles/globals.less"
import styles from '../styles/Home.module.css'
import AutoComplete from '../components/Autocomplete'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChevronRight } from "@fortawesome/free-solid-svg-icons";

import moment from 'moment';


export default function Cart() {
  
  return (
    <div>
      <Head>
        <title>Your Cart - City of Bounce</title>
        <meta
          property="og:title"
          content={"Party Rentals | Bounce Houses | Tents - City of Bounce"}
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id={styles.content}>
          Cart
        </div>
    </div>
  )
}
